#!/bin/sh

# This script compiles java code, first replacing loops with recursive methods.

# Intermediate code is placed in "spooned" folder by default. Can be overridden with "-o new_folder" switch.


DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

COMPILE_LIB="$DIR/compiler-lib/spoon-core-1.4-jar-with-dependencies.jar"
CLASS_LIB="."
COMPILER_SRC="$DIR/dist/loops2rec.jar"
EXTRA_LIB=""

EXTRACP="$COMPILE_LIB:$CLASS_LIB:$COMPILER_SRC:$EXTRA_LIB:$2"

mkdir -p spooned
java -cp $EXTRACP \
	aeminium.java.compiler.ltr.launcher.LTRCompilerLauncher \
	 --compliance 6 \
	 --compile \
	 --template $DIR/compiler-src/ \
	 --build . \
	 -i $3